name: R-CI

on:
  push:
    branches: [ Andre ]
  pull_request:
    branches: [ Andre ]

defaults:
  run:
    working-directory: geoDBapi  # your package folder

jobs:
  R-CI-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install specific packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::httr
            any::tidygeocoder
            any::testthat
            any::roxygen2

      # Build & check the package
      - uses: r-lib/actions/check-r-package@v2
        with:
          args: '--no-build-vignettes'